In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2024-12-18 12:49:19.960941: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-18 12:49:19.982823: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-18 12:49:20.179923: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-18 12:49:20.428026: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1734506360.593301   24803 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734506360.63

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6706, 6837, 4247, 9343],
 [6706, 6837, 4247, 3791],
 [6706, 6544, 4247, 2300],
 [7003, 821, 2244, 2591, 9949],
 [7003, 821, 2244, 2591, 8976],
 [4514, 6706, 4946, 4247, 1241],
 [2202, 7876, 4048, 2591]]

In [9]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [15]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6706 6837 4247 9343]
 [   0    0    0    0 6706 6837 4247 3791]
 [   0    0    0    0 6706 6544 4247 2300]
 [   0    0    0 7003  821 2244 2591 9949]
 [   0    0    0 7003  821 2244 2591 8976]
 [   0    0    0 4514 6706 4946 4247 1241]
 [   0    0    0    0 2202 7876 4048 2591]]


In [16]:
## feature representation
dim=10

In [18]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step


array([[[-0.01706064,  0.00288226, -0.04962698,  0.03687948,
         -0.0126936 , -0.04746411,  0.01501192,  0.02659493,
         -0.03345716,  0.03654039],
        [-0.01706064,  0.00288226, -0.04962698,  0.03687948,
         -0.0126936 , -0.04746411,  0.01501192,  0.02659493,
         -0.03345716,  0.03654039],
        [-0.01706064,  0.00288226, -0.04962698,  0.03687948,
         -0.0126936 , -0.04746411,  0.01501192,  0.02659493,
         -0.03345716,  0.03654039],
        [-0.01706064,  0.00288226, -0.04962698,  0.03687948,
         -0.0126936 , -0.04746411,  0.01501192,  0.02659493,
         -0.03345716,  0.03654039],
        [-0.03925937, -0.00930564, -0.02986604, -0.03991898,
          0.00144903,  0.00055741, -0.02058177, -0.02968436,
          0.02047944, -0.01469611],
        [-0.01909386,  0.00843726,  0.04962349,  0.04418129,
          0.0315775 ,  0.03238178, -0.00030823, -0.0210632 ,
          0.01668769, -0.00175703],
        [-0.04602379,  0.04310963,  0.04867395, -0.0

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 6706, 6837, 4247, 9343], dtype=int32)

In [28]:
# model.predict(embedded_docs[0][0])